### ISSUE TITLE
Enhancement: Make it possible to edit entries 

### ISSUE THREAD

**Issue by MaluNoPeleke** [supechicken/ChromeOS-AutoStart#11]
If I want to edit a command/entry I have to delete it and create a new one.
Better would be an editing function of the original command/entry for this.

**Comment by supechicken** [comment]
The ability to modify existing entries has been added to the latest release ([v5.1](https://github.com/supechicken/ChromeOS-AutoStart/releases/tag/v5.1)) now 😀
