### ISSUE TITLE
Thank you for this brilliant extension!

### ISSUE THREAD

**Issue by TroubleDog54** [supechicken/ChromeOS-AutoStart#13]
Hello!

I setup a seperate VM for my work programs so that I can mess around safely in the default termina VM without kicking myself in the ass every time I wanted to work. Unfortunately, ChromeOS doesn't automatically share folders with VM's other than the default termina VM, so I would have had to manually share my folders each time with the `vmc share` command. However, I discovered this extension today and it works perfectly! I can now work in peace. 

Thank you so much for your work this extension, I wish you the best of days!

**Comment by supechicken** [comment]
Glad to know that it is useful to you!
