### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by Heath123** [supechicken/ChromeOS-AutoStart#2]
I have a command set:
![image](https://user-images.githubusercontent.com/13787163/128426850-a4a3c4c7-cdc4-4318-b766-3fd52082ae82.png)
but when I press the Test button it just opens a blank window:
![image](https://user-images.githubusercontent.com/13787163/128426922-6ae5352f-991d-4a1d-9a34-a9e203a23bad.png)
and the command doesn't run, when testing or at startup

**Comment by Heath123** [comment]
Just realised that I can open the dev tools on the blank window:
![image](https://user-images.githubusercontent.com/13787163/128427205-9dce22c1-71b2-43f1-ba21-bd1ca0712af0.png)

**Comment by supechicken** [comment]
Seems your extension id is not the secure shell one, could you try to follow the instructions with this readme:

https://github.com/supechicken/ChromeOS-AutoStart/raw/d9e540f828b228b0921082f4a323e3d56fd90f62/README.md

**Comment by Heath123** [comment]
Do I need to remove secure shell before I install it?

**Comment by Heath123** [comment]
It works when loading from unpacked, thank you

**Comment by daemonspudguy** [comment]
Now I'm wondering how this can be packed so it actually loads at boot.

**Comment by supechicken** [comment]
@daemonspudguy The extension will fire the `chrome.runtime.onStartup` block  (loading from packed is not required to use the api)
