### ISSUE TITLE
Autostart window doesnt auto close

### ISSUE THREAD

**Issue by Apacelus** [supechicken/ChromeOS-AutoStart#5]
After logging in, the autostart window appears, but doesnt go away after the command is finished. The console shows this error:
```
Error in event handler: TypeError: output.split is not a function
    at chrome-extension://algkcnfjnajfhgimadimbjhmpaeohhln/run.js:7:22
    at extensions::terminalPrivate:10:9
```

**Comment by supechicken** [comment]
This is due to a recent changes in the `terminalPrivate` API (the output of the process will be returned as an `ArrayBuffer` instead of a `string` now). I will fix it in next commit when I figured out how to convert it to `string`

**Comment by supechicken** [comment]
(see https://chromium-review.googlesource.com/c/apps/libapps/+/3470612/ for more info)

**Comment by supechicken** [comment]
Hello! Could you check if the latest version ([v3.0](https://github.com/supechicken/ChromeOS-AutoStart/releases/tag/v3.0)) works? The issue should be fixed now :)

**Comment by Apacelus** [comment]
Yes, the issue is gone.

**Comment by supechicken** [comment]
(notice that the `v3.0` release may not work on every system (reports `Invalid value for state` on my another Chrome OS machine), please use `v3.0.1` if the command doesn't run probably)
