### ISSUE TITLE
Creating/copying files to write protected folders doesnt work

### ISSUE THREAD

**Issue by Apacelus** [supechicken/ChromeOS-AutoStart#7]
Trying to copy to write protected folders, doesnt do anything. Entered this command into the extension: ```sudo touch /etc/init.d/test.txt``` After running "testing" the command, this is the result in the crosh terminal:
```
chronos@localhost / $ sudo ls -a /etc/init.d/
.  ..  functions.sh
```

**Comment by Apacelus** [comment]
@supechicken

**Comment by supechicken** [comment]
Could you provide the output of the inspect console in debug mode? (retype the current command, check `Debug mode` and press <kbd>Enter</kbd> to enter debug mode)

**Comment by Apacelus** [comment]
Here is the log: [console.log](https://github.com/supechicken/ChromeOS-AutoStart/files/8516747/console.log)
Chromeos version: Version 101.0.4951.32 (Official Build) beta (64-bit)

**Comment by supechicken** [comment]
Could you upload the output of `/home/chronos/user/nohup.out` also?

**Comment by Apacelus** [comment]
```bash: warning: stdin: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md```

I was unsure if its this extension throwing the error, so I deleted the nohup.out file, ran the extension and then grabbed it immediately. Did that twice, same results both times.

P.S: The same error as when running a script from the user partition...

**Comment by supechicken** [comment]
Oh sorry, it is a text file (click the test button on the extension to regenerate it):
`cat /home/chronos/user/nohup.out`

**Comment by Apacelus** [comment]
No, the above is the output inside the file, I just copy pasted it instead of uploading. Sorry for making it seem like an error in accessing the file
Thats what it looks like in the console:
```
chronos@localhost / $ sudo cat /home/chronos/user/nohup.out
bash: warning: stdin: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md
```

**Comment by Apacelus** [comment]
btw, just made my rootfs rw(to install my fan control script) and tested the extension again, same results. The file did not get created and nohup.out output is the same.

**Comment by supechicken** [comment]
Maybe try using this command instead of `touch` and see if it works:
```shell
sudo bash -x 'echo > /etc/init.d/test.txt'
```

(If it doesn't work either, paste the output of `cat ~/nohup.out` here)

**Comment by Apacelus** [comment]
Here is [console.log](https://github.com/supechicken/ChromeOS-AutoStart/files/8517910/console.log) and [nohup.out.txt](https://github.com/supechicken/ChromeOS-AutoStart/files/8517925/nohup.out.txt) for the "new" command.

**Comment by supechicken** [comment]
Try using this branch: https://github.com/supechicken/ChromeOS-AutoStart/tree/no_nohup (upload `console.log` if this still not working)

**Comment by Apacelus** [comment]
It works now. But there is another issue I found. It doesnt work if I set a chronos password. If I set a chronos password(run ```chromeos-setdevpasswd``` as root), then I get the following [console.log](https://github.com/supechicken/ChromeOS-AutoStart/files/8518042/console.log)

**Comment by supechicken** [comment]
> It works now. But there is another issue I found. It doesnt work if I set a chronos password. If I set a chronos password(run `chromeos-setdevpasswd` as root), then I get the following [console.log](https://github.com/supechicken/ChromeOS-AutoStart/files/8518042/console.log)

You can tell `sudo` to read password from stdin:
```shell
sudo -S touch /etc/init.d/test.txt <<< "password"
```

**Comment by Apacelus** [comment]
Today chromeos updated again and now it doesnt work again. I am using the [nohup-branch](https://github.com/supechicken/ChromeOS-AutoStart/tree/no_nohup). This is the command(my real password is replaced with "password"): `sudo -S bash /usr/local/Fanctrl/install.sh <<< "password"`
[install.sh](https://github.com/Fornball/chromeos-autofanctrl/blob/main/install.sh)
[console.log](https://github.com/supechicken/ChromeOS-AutoStart/files/8553369/console.log)

**Comment by supechicken** [comment]
> Today chromeos updated again and now it doesnt work again. I am using the [nohup-branch](https://github.com/supechicken/ChromeOS-AutoStart/tree/no_nohup). This is the command(my real password is replaced with "password"): `sudo -S bash /usr/local/Fanctrl/install.sh <<< "password"` [install.sh](https://github.com/Fornball/chromeos-autofanctrl/blob/main/install.sh) [console.log](https://github.com/supechicken/ChromeOS-AutoStart/files/8553369/console.log)

Hmm... I don't see any issue in console.log. Maybe try to put all commands in a script and run it in the extension with `bash -x <script>`?

**Comment by Apacelus** [comment]
> Maybe try to put all commands in a script and run it


I was already doing that.  

My system just updated again(thereby locking rootfs again), so I tried this command: ```sudo -S bash -x /usr/local/Fanctrl/install.sh <<< "password"``` but it didnt work either.
[console.txt](https://github.com/supechicken/ChromeOS-AutoStart/files/8602488/console.txt)
[install.sh](https://github.com/Fornball/chromeos-autofanctrl/blob/main/install.sh)

**Comment by supechicken** [comment]
Have you remounted the root filesystem as read/write? As I know the rootFS verification will re-enable automatically (you may need to disable the rootFS verification manually after each update)

**Comment by Apacelus** [comment]
I thought the whole point of this project was to be able to modify system files without removing the rootfs verification?
> An extension for running shell command at ChromeOS startup automatically without removing RootFS verification.

**Comment by supechicken** [comment]
> I thought the whole point of this project was to be able to modify system files without removing the rootfs verification?
> 
> > An extension for running shell command at ChromeOS startup automatically without removing RootFS verification.

This extension allows you to *autostart* a command/script at startup without remounting the system as r/w only... (if you need to apply some modification to the filesystem you still need to remount the filesystem)

Seems that you are trying to install and start the fancontrol service via the extension ( correct me if I am wrong :) ) As an alternative, you could just run the fancontrol command in the extension, the command will run continue running in the background  (by that way you don't need to modify the filesystem) (notice that you need to use the extension **in default branch** to get it running in the background after the extension window close)
