### ISSUE TITLE
Warning on the manifest

### ISSUE THREAD

**Issue by iz0eyj** [supechicken/ChromeOS-AutoStart#8]
Hello,
your extension works wonders, and I believe that for ChromeOS users it pairs with U-Block on the utility podium.
However, by now Chrome signals a warning, nothing to worry about because it does not prevent its functioning but I still think it useful to report it to you:

`Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.`

Regards, Federico

**Comment by supechicken** [comment]
Thank you for your support! (And sorry for this very late reply)

I have just added Manifest V3 support to the latest version of my extension :)
