### ISSUE TITLE
Auto start crostini and a linux app at startup?

### ISSUE THREAD

**Issue by Arjay56** [supechicken/ChromeOS-AutoStart#9]
According to Googles' ChromeOS Linux FAQ, penguin is disabled intentionally at system startup and MUST be manually started.  I would love to have penguin autostart- which i believe  (possibly incorrectly) is what your code is supposed to do.  I would love to automatically launch crostini and my Google Drive syncronizer- Insync.  Is this possible, or is my desired end result incorrectly making me think that it could be?  Please correctly set my expectations for your code.

Thanks,
RJ

**Comment by supechicken** [comment]
> supposed to do

This extension is initially designed for autostarting commands in **the Chrome OS system shell**, **NOT** Crostini (they are not the same thing)

> Auto start Crostini

Although this extension is not designed for that, you can modify it to make it works on Crostini:

- Replace the `shell` command with `vmc start termina; lxc exec penguin -- /bin/bash` (in `run.js`) to autorun a command in Crostini instead of the developer shell

**Comment by MaluNoPeleke** [comment]
For me just an empty window opens up with ChromeOS v110. Is there anything you could do about it?
![image](https://user-images.githubusercontent.com/1446541/214699084-e4516f03-2e90-4c98-be22-11cf5ac074a7.png)
I want to start Vivaldi Browser automatically by running `vmc start termina; lxc exec penguin -- /bin/bash (vivaldi) `

**Comment by supechicken** [comment]
> Although this extension is not designed for that, you can modify it to make it works on Crostini:
> 
> Replace the `shell` command with `vmc start termina; lxc exec penguin -- /bin/bash` (**>>>>in `run.js`<<<<**) to autorun a command in Crostini instead of the developer shell

**Comment by MaluNoPeleke** [comment]
Okay, changed it to `vmc start termina; lxc exec penguin -- vivaldi` but still no success.

**Comment by supechicken** [comment]
Hi @Arjay56 and @MaluNoPeleke, the latest version of ChromeOS-AutoStart has Crostini support out of the box now. (not sure if it is still helpful to you 😅)

**Comment by shivshankar3578** [comment]
@supechicken share the command example please
